### ISSUE TITLE
Highlight drops in Chart

### ISSUE THREAD

**Issue by kaihendry** [kaihendry/lesshero#1]
For example go Green when it gets less https://echarts.apache.org/examples/en/editor.html?c=line-sections

**Comment by r2p2** [comment]
I am not familiar with go and the chart library but found the program useful and wanted to take a deeper look.

Am I correct in the assumption that using VisualMaps referenced in the example will always result in those additional colored sections in the chart besides coloring the lines? I am not sure if that is a desired outcome. I have a working solution which needs a bit of fine tuning which only colors the affected line sections.

It is somewhat cheated, since I draw relevant sections of a second line over the existing one with a different color. But besides VisualMaps that was the only way I found to color line sections differently.

**Comment by r2p2** [comment]
I managed to modify the go-echart library so that I can replicate the echart example. In case my pull requests get applied, I will open a pull request to this repository using `VisualMap` so we don't have to draw two lines.

**Comment by kaihendry** [comment]
Thank you @systemb4
